//先抓到畫面上的cv元素
var canvas = document.getElementById("mycanvas")
var ctx = canvas.getContext("2d")

//設定尺寸
canvas.width= 400
canvas.height= 400

var time=0
function draw(){
  time++
  ctx.clearRect(0,0,400,400) //清除畫布上的軌跡

  //座標繪製
  ctx.beginPath()
  for(var i=0;i<10;i++){
    let pos = i*50 //每格50劃一條線
    ctx.moveTo(pos,0) //x軸起點
    ctx.lineTo(pos,400) //x軸終點
    ctx.fillText(pos,pos,10) //x軸繪製文字(內容,x位置,y位置)
    //
    ctx.moveTo(0,pos) //y軸起點
    ctx.lineTo(400,pos) //y軸終點
    ctx.fillText(pos,10,pos) //y軸繪製文字(內容,x位置,y位置)
  }
  ctx.strokeStyle = "rgba(0,0,0,0.1)"
  ctx.stroke()
  
  //地面上的線
  ctx.beginPath() //清掉先前路徑
  ctx.moveTo(50,350)
  ctx.lineTo(350,350)
  ctx.lineWidth = 2 //被吃掉看不到，所以增加寬度
  ctx.strokeStyle="black" //原先沿用到上個色彩設定，所以改回來黑色
  ctx.stroke()
  //煙霧1
  let carx = time%440-40
  ctx.beginPath()
  ctx.arc(297,10-carx,6,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(283,10-carx,8,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,16-carx,10,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,6-carx,7,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  //煙霧2  
  ctx.beginPath()
  ctx.arc(297,60-carx,6,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(283,60-carx,8,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,66-carx,10,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,56-carx,7,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  //煙霧3  
  ctx.beginPath()
  ctx.arc(297,110-carx,6,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(283,110-carx,8,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,116-carx,10,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,106-carx,7,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  //煙霧4  
  ctx.beginPath()
  ctx.arc(297,160-carx,6,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(283,160-carx,8,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,166-carx,10,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,156-carx,7,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  //煙霧5  
  ctx.beginPath()
  ctx.arc(297,210-carx,6,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(283,210-carx,8,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,216-carx,10,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,206-carx,7,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
   //煙霧6
  ctx.beginPath()
  ctx.arc(297,260-carx,6,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(283,260-carx,8,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,266-carx,10,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  ctx.beginPath()
  ctx.arc(290,256-carx,7,0,Math.PI*2)  
  ctx.fillStyle="black"
  ctx.fill()
  ctx.stroke()
  //房子體
  ctx.beginPath()
  ctx.moveTo(50,350)
  ctx.lineTo(350,350)
  ctx.lineTo(350,150)
  ctx.lineTo(50,150)
  ctx.closePath()
  ctx.fillStyle="#ffe4c4"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //屋頂
  ctx.beginPath()
  ctx.moveTo(30,170)
  ctx.lineTo(370,170)
  ctx.lineTo(330,100)
  ctx.lineTo(70,100)
  ctx.closePath()
  ctx.fillStyle="#ffa07a"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //底下那一槓
  ctx.beginPath()
  ctx.moveTo(50,350)
  ctx.lineTo(350,350)
  ctx.lineTo(350,330)
  ctx.lineTo(50,330)
  ctx.closePath()
  ctx.fillStyle="#ffa07a"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //中間那一槓
  ctx.beginPath()
  ctx.moveTo(50,260)
  ctx.lineTo(350,260)
  ctx.lineTo(350,240)
  ctx.lineTo(50,240)
  ctx.closePath()
  ctx.fillStyle="#ffa07a"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //中間那一塊
  ctx.beginPath()
  ctx.moveTo(150,350)
  ctx.lineTo(250,350)
  ctx.lineTo(250,240)
  ctx.lineTo(150,240)
  ctx.closePath()
  ctx.fillStyle="#ffe4c4"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //門後
  ctx.beginPath()
  ctx.moveTo(175,350)
  ctx.lineTo(225,350)
  ctx.lineTo(225,300)
  ctx.lineTo(175,300)
  ctx.closePath()
  ctx.fillStyle="#808080"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //左門
  ctx.beginPath()
  ctx.moveTo(175-mouse.y/25,350)
  ctx.lineTo(200-mouse.y/25,350)
  ctx.lineTo(200-mouse.y/25,300)
  ctx.lineTo(175-mouse.y/25,300)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //右門
  ctx.beginPath()
  ctx.moveTo(225+mouse.y/25,350)
  ctx.lineTo(200+mouse.y/25,350)
  ctx.lineTo(200+mouse.y/25,300)
  ctx.lineTo(225+mouse.y/25,300)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //中間三角形
  ctx.beginPath()
  ctx.moveTo(130,250)
  ctx.lineTo(270,250)
  ctx.lineTo(200,190)
  ctx.closePath()
  ctx.fillStyle="#ffa07a"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //中窗
  ctx.beginPath()
  ctx.moveTo(180,280)
  ctx.lineTo(220,280)
  ctx.lineTo(220,260)
  ctx.lineTo(180,260)
  ctx.closePath()
  ctx.fillStyle="#f5f5f5"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //左下左下窗
  ctx.beginPath()
  ctx.moveTo(75,320)
  ctx.lineTo(100,320)
  ctx.lineTo(100,295)
  ctx.lineTo(75,295)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //左下右下窗
  ctx.beginPath()
  ctx.moveTo(100,320)
  ctx.lineTo(125,320)
  ctx.lineTo(125,295)
  ctx.lineTo(100,295)
  ctx.closePath()
  ctx.fillStyle="#f5f5f5"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //左下右上窗
  ctx.beginPath()
  ctx.moveTo(100,295)
  ctx.lineTo(125,295)
  ctx.lineTo(125,270)
  ctx.lineTo(100,270)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //左下左上窗
  ctx.beginPath()
  ctx.moveTo(75,270)
  ctx.lineTo(100,270)
  ctx.lineTo(100,295)
  ctx.lineTo(75,295)
  ctx.closePath()
  ctx.fillStyle="#f5f5f5"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //右下左下窗
  ctx.beginPath()
  ctx.moveTo(275,320)
  ctx.lineTo(300,320)
  ctx.lineTo(300,295)
  ctx.lineTo(275,295)
  ctx.closePath()
  ctx.fillStyle="#f5f5f5"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //右下右下窗
  ctx.beginPath()
  ctx.moveTo(300,320)
  ctx.lineTo(325,320)
  ctx.lineTo(325,295)
  ctx.lineTo(300,295)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //右下右上窗
  ctx.beginPath()
  ctx.moveTo(300,295)
  ctx.lineTo(325,295)
  ctx.lineTo(325,270)
  ctx.lineTo(300,270)
  ctx.closePath()
  ctx.fillStyle="#f5f5f5"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //右下左上窗
  ctx.beginPath()
  ctx.moveTo(275,270)
  ctx.lineTo(300,270)
  ctx.lineTo(300,295)
  ctx.lineTo(275,295)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //右上左下窗
  ctx.beginPath()
  ctx.moveTo(275,230)
  ctx.lineTo(300,230)
  ctx.lineTo(300,205)
  ctx.lineTo(275,205)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //右上右下窗
  ctx.beginPath()
  ctx.moveTo(300,230)
  ctx.lineTo(325,230)
  ctx.lineTo(325,205)
  ctx.lineTo(300,205)
  ctx.closePath()
  ctx.fillStyle="#f5f5f5"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //右上右上窗
  ctx.beginPath()
  ctx.moveTo(300,205)
  ctx.lineTo(325,205)
  ctx.lineTo(325,180)
  ctx.lineTo(300,180)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //右上左上窗
  ctx.beginPath()
  ctx.moveTo(275,205)
  ctx.lineTo(300,205)
  ctx.lineTo(300,180)
  ctx.lineTo(275,180)
  ctx.closePath()
  ctx.fillStyle="#f5f5f5"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //左上左下窗
  ctx.beginPath()
  ctx.moveTo(75,230)
  ctx.lineTo(100,230)
  ctx.lineTo(100,205)
  ctx.lineTo(75,205)
  ctx.closePath()
  ctx.fillStyle="#f5f5f5"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //左上右下窗
  ctx.beginPath()
  ctx.moveTo(100,230)
  ctx.lineTo(125,230)
  ctx.lineTo(125,205)
  ctx.lineTo(100,205)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //左上右上窗
  ctx.beginPath()
  ctx.moveTo(100,205)
  ctx.lineTo(125,205)
  ctx.lineTo(125,180)
  ctx.lineTo(100,180)
  ctx.closePath()
  ctx.fillStyle="#f5f5f5"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //左上左上窗
  ctx.beginPath()
  ctx.moveTo(75,205)
  ctx.lineTo(100,205)
  ctx.lineTo(100,180)
  ctx.lineTo(75,180)
  ctx.closePath()
  ctx.fillStyle="#e0ffff"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //煙囪
  ctx.beginPath()
  ctx.moveTo(275,120)
  ctx.lineTo(305,120)
  ctx.lineTo(305,70)
  ctx.lineTo(275,70)
  ctx.closePath()
  ctx.fillStyle="#ffa07a"
  ctx.fill()
  ctx.strokeStyle="black"
  ctx.stroke()
  //確認滑鼠事件有抓取到
  ctx.beginPath()
  ctx.arc(mouse.x,mouse.y,5,0,Math.PI*2)
  ctx.fillStyle="black"
  ctx.fill()
}

setInterval(draw,20)

var mouse = {
  x: 0,
  y: 0
}

canvas.addEventListener("mousemove",function(evt){
  mouse.x = evt.offsetX  //相對於畫布上的距離
  mouse.y = evt.offsetY
})